server:
  port: 18092
spring:
  application:
    name: comment
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.211.132:3306/changgou_comment?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
  main:
    allow-bean-definition-overriding: true
  redis:
    host: 192.168.211.132
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    #默认情况下，拿到的地址是主机名，设置为true注册Eureka时使用ip:127.0.0.1
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true